java_test(
    name = "TimerTest",
    srcs = ["TimerTest.java"],
    test_class = "believe.core.TimerTest",
    deps = [
        "//src/believe/core",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)
