java_test(
    name = "TimerTest",
    srcs = ["TimerTest.java"],
    test_class = "believe.core.TimerTest",
    deps = [
        "//lib:hamcrest",
        "//lib:junit",
        "//src/believe/core",
    ],
)
