java_library(
    name = "collidable",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/map/gui:__pkg__",
        "//java/believe/map/io:__pkg__",
        "//java/believe/physics/collision:__pkg__",
        "//javatests/believe:believe_tests",
    ],
    deps = [
        "//java/believe/geometry",
        "//java/believe/map/io:map_entity_generator",
        "//java/believe/physics/collision",
        "//java/believe/statemachine",
        "//third_party/slick",
    ],
)
