package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "protodata",
    srcs = [
        "BinaryProtoFileUtil.java",
        "MutableProtoDataCommitter.java",
    ],
    deps = [
        "//java/believe/datamodel",
        "//third_party/proto",
        "//third_party/slick",
    ],
)
