package(
    default_visibility = ["//:__pkg__"],
)

java_library(
    name = "editor",
    srcs = glob(["*.java"]),
    deps = [
        "//src/believe/app",
        "//src/believe/app/flag_parsers",
        "//src/believe/app/flags",
        "//src/believe/gamestate",
        "//src/believe/util",
    ],
)
