package(
    default_visibility = ["//:believe_all_pkgs"],
)

proto_library(
    name = "map_metadata_proto",
    srcs = ["map_metadata.proto"],
)

java_proto_library(
    name = "map_metadata_java_proto",
    deps = [":map_metadata_proto"],
)
