java_test(
    name = "CrossFadeTransitionTest",
    srcs = ["CrossFadeTransitionTest.java"],
    deps = [
        "//java/believe/graphics_transitions",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
