package(
    default_testonly = True,
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "testing",
    srcs = ["FakeFontLoader.java"],
    deps = [
        "//java/believe/core/io",
        "//third_party/slick",
    ],
)
