package(
    default_testonly = 1,
    default_visibility = ["//visibility:private"],
)

java_test(
    name = "LogMessageListSubjectTest",
    srcs = ["LogMessageListSubjectTest.java"],
    deps = [
        "//java/believe/logging/testing",
        "//java/believe/logging/truth",
        "//java/believe/logging/truth:package_info",
        "//third_party/truth",
    ],
)

java_test(
    name = "VerifiableLogSystemSubjectTest",
    srcs = ["VerifiableLogSystemSubjectTest.java"],
    deps = [
        "//java/believe/logging/testing",
        "//java/believe/logging/truth",
        "//java/believe/logging/truth:package_info",
        "//third_party/junit",
        "//third_party/truth",
    ],
)
