java_library(
    name = "debug",
    srcs = glob(["*.java"]),
    deps = [
        "//java/believe/levelFlow/parsing",
        "//java/believe/levelFlow/parsing/exceptions",
        "//third_party/slick",
    ],
)
