package(
    default_visibility = ["//:believe_all_pkgs"],
)

proto_library(
    name = "game_options",
    srcs = ["game_options.proto"],
)

java_proto_library(
    name = "game_options_java_proto",
    deps = [":game_options"],
)
