java_library(
    name = "base",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character/base:__pkg__",
        "//src/musicGame/geometry:__pkg__",
        "//src/musicGame/gui:__pkg__",
        "//src/musicGame/levelFlow/component:__pkg__",
        "//src/musicGame/map/gui:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/geometry",
    ],
)
