java_library(
    name = "gamestate",
    srcs = glob(["*.java"]),
    visibility = ["//src/believe:__pkg__"],
    deps = [
        "//lib",
        "//src/believe/character/playable",
        "//src/believe/core",
        "//src/believe/gui",
        "//src/believe/levelFlow/component",
        "//src/believe/levelFlow/parsing",
        "//src/believe/levelFlow/parsing/exceptions",
        "//src/believe/map/gui",
        "//src/believe/physics/manager",
        "//src/believe/util",
    ],
)
