java_test(
    name = "ConcurrentStateMachineTest",
    srcs = ["ConcurrentStateMachineTest.java"],
    test_class = "believe.statemachine.ConcurrentStateMachineTest",
    deps = [
        "//lib:mockito",
        "//src/believe/statemachine",
        "//src/believe/util",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "EntityStateMachineTest",
    srcs = ["EntityStateMachineTest.java"],
    test_class = "believe.statemachine.EntityStateMachineTest",
    deps = [
        "//lib:mockito",
        "//src/believe/statemachine",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "StateTest",
    srcs = ["StateTest.java"],
    test_class = "believe.statemachine.StateTest",
    deps = [
        "//lib:mockito",
        "//src/believe/statemachine",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "TransitionTest",
    srcs = ["TransitionTest.java"],
    test_class = "believe.statemachine.TransitionTest",
    deps = [
        "//lib:mockito",
        "//src/believe/statemachine",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
