java_test(
    name = "IntegerFlagParserTest",
    srcs = ["IntegerFlagParserTest.java"],
    test_class = "believe.app.flag_parsers.IntegerFlagParserTest",
    deps = [
        "//lib:hamcrest",
        "//lib:junit",
        "//src/believe/app/flag_parsers",
    ],
)

java_test(
    name = "BooleanFlagParserTest",
    srcs = ["BooleanFlagParserTest.java"],
    test_class = "believe.app.flag_parsers.BooleanFlagParserTest",
    deps = [
        "//lib:hamcrest",
        "//lib:junit",
        "//src/believe/app/flag_parsers",
    ],
)

java_test(
    name = "CommandLineParserTest",
    srcs = ["CommandLineParserTest.java"],
    test_class = "believe.app.flag_parsers.CommandLineParserTest",
    deps = [
        "//lib:hamcrest",
        "//lib:junit",
        "//src/believe/app/flag_parsers",
    ],
)
