load("//bazel/bzl:rules.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "RectangleTest",
    srcs = ["RectangleTest.kt"],
    deps = [
        "//java/believe/geometry",
        "//third_party/truth",
    ],
)
