java_library(
    name = "geometry",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character/base:__pkg__",
        "//src/musicGame/core/display:__pkg__",
        "//src/musicGame/gui/base:__pkg__",
        "//src/musicGame/levelFlow/component:__pkg__",
        "//src/musicGame/map/collidable:__pkg__",
        "//src/musicGame/physics/collision:__pkg__",
        "//src/musicGame/util:__pkg__",
        "//test/musicGame/geometry:__pkg__",
        "//test/musicGame/physics/collision:__pkg__",
        "//test/musicGame/util:__pkg__",
    ],
    deps = ["//lib"],
)
