java_library(
    name = "geometry",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character:character_pkg",
        "//src/musicGame/core/display:__pkg__",
        "//src/musicGame/gui:__pkg__",
        "//src/musicGame/levelFlow/component:__pkg__",
        "//src/musicGame/map/collidable:__pkg__",
        "//src/musicGame/physics/collision:__pkg__",
        "//src/musicGame/util:__pkg__",
        "//test/musicGame:believe_tests",
    ],
    deps = ["//lib"],
)
