java_test(
    name = "TileCollisionHandlerTest",
    srcs = ["TileCollisionHandlerTest.java"],
    test_class = "musicGame.physics.collision.TileCollisionHandlerTest",
    deps = [
        "//lib:mockito",
        "//src/musicGame/geometry",
        "//src/musicGame/map/collidable",
        "//src/musicGame/physics/collision",
        "//src/musicGame/physics/collision:handlers",
        "@junit//jar",
    ],
)
