java_test(
    name = "PhysicsManagerTest",
    srcs = ["PhysicsManagerTest.java"],
    test_class = "musicGame.physics.manager.PhysicsManagerTest",
    deps = [
        "//lib:mockito",
        "//src/musicGame/physics/collision",
        "//src/musicGame/physics/gravity",
        "//src/musicGame/physics/manager",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
