java_library(
    name = "component",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/gamestate:__pkg__",
        "//src/believe/gui:__pkg__",
        "//src/believe/levelFlow/parsing:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = [
        "//lib",
        "//src/believe/core",
        "//src/believe/core/display",
        "//src/believe/core/io",
        "//src/believe/geometry",
        "//src/believe/gui",
    ],
)
