java_library(
    name = "collidable",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/map/gui:__pkg__",
        "//src/believe/map/io:__pkg__",
        "//src/believe/physics/collision:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = [
        "//lib",
        "//src/believe/geometry",
        "//src/believe/map/io:map_entity_generator",
        "//src/believe/physics/collision",
        "//src/believe/statemachine",
    ],
)
