java_test(
    name = "PhysicsManagerTest",
    srcs = ["PhysicsManagerTest.java"],
    test_class = "believe.physics.manager.PhysicsManagerTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//lib/mockito",
        "//src/believe/physics/collision",
        "//src/believe/physics/gravity",
        "//src/believe/physics/manager",
    ],
)
