java_test(
    name = "PhysicsManagerTest",
    srcs = ["PhysicsManagerTest.java"],
    test_class = "believe.physics.manager.PhysicsManagerTest",
    deps = [
        "//src/believe/physics/collision",
        "//src/believe/physics/gravity",
        "//src/believe/physics/manager",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
    ],
)
