java_test(
    name = "MapPropertiesTest",
    srcs = ["MapPropertiesTest.java"],
    deps = [
        "//java/believe/map/io:properties",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
