java_library(
    name = "component",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/gamestate:__pkg__",
        "//src/musicGame/gui:__pkg__",
        "//src/musicGame/levelFlow/parsing:__pkg__",
        "//test/musicGame/gui:__pkg__",
        "//test/musicGame/levelFlow/component:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/core",
        "//src/musicGame/geometry",
        "//src/musicGame/gui/base",
    ],
)
