package(
    default_visibility = ["//:believe_all_pkgs"],
)

proto_library(
    name = "command_sequence_proto",
    srcs = ["command_sequence.proto"],
)

java_proto_library(
    name = "command_sequence_java_proto",
    deps = [":command_sequence_proto"],
)
