java_library(
    name = "gravity",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/physics/collision:__pkg__",
        "//src/believe/physics/manager:__pkg__",
        "//test/believe:believe_tests",
    ],
)
