java_test(
    name = "FlowComponentBuilderTest",
    srcs = ["FlowComponentBuilderTest.java"],
    deps = [
        "//java/believe/levelFlow/parsing",
        "//java/believe/levelFlow/parsing/exceptions",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "FlowFileParserIntegrationTest",
    srcs = ["FlowFileParserIntegrationTest.java"],
    deps = [
        "//java/believe/levelFlow/parsing",
        "//java/believe/levelFlow/parsing/exceptions",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/slick",
    ],
)

java_test(
    name = "FlowFileParserTest",
    srcs = ["FlowFileParserTest.java"],
    deps = [
        "//java/believe/levelFlow/parsing",
        "//java/believe/levelFlow/parsing/exceptions",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "FlowFileTokenizerTest",
    srcs = ["FlowFileTokenizerTest.java"],
    deps = [
        "//java/believe/levelFlow/parsing",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)

java_test(
    name = "LineParserTest",
    srcs = ["LineParserTest.java"],
    deps = [
        "//java/believe/levelFlow/parsing",
        "//java/believe/levelFlow/parsing/exceptions",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)
