java_library(
    name = "exceptions",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/core/action:__pkg__",
        "//src/believe/debug:__pkg__",
        "//src/believe/gamestate:__pkg__",
        "//src/believe/levelFlow/parsing:__pkg__",
        "//test/believe:believe_tests",
    ],
)
