java_test(
    name = "PhysicsManagerTest",
    srcs = ["PhysicsManagerTest.java"],
    deps = [
        "//java/believe/physics/collision",
        "//java/believe/physics/gravity",
        "//java/believe/physics/manager",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
    ],
)
