java_test(
    name = "DamageProjectionTest",
    srcs = ["DamageProjectionTest.java"],
    deps = [
        "//java/believe/character",
        "//java/believe/character/playable",
        "//java/believe/character/playable:package-info",
        "//java/believe/physics/manager",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
