java_test(
    name = "ComboSyncherTest",
    srcs = ["ComboSyncherTest.java"],
    test_class = "musicGame.gui.ComboSyncherTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/core",
        "//src/musicGame/gui",
        "//src/musicGame/levelFlow/component",
        "@junit//jar",
    ],
)

java_test(
    name = "DirectionalPanelTest",
    srcs = ["DirectionalPanelTest.java"],
    test_class = "musicGame.gui.DirectionalPanelTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/gui",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "MenuSelectionGroupTest",
    srcs = ["MenuSelectionGroupTest.java"],
    test_class = "musicGame.gui.MenuSelectionGroupTest",
    deps = [
        "//lib:mockito",
        "//src/musicGame/gui",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "NumberPickerTest",
    srcs = ["NumberPickerTest.java"],
    test_class = "musicGame.gui.NumberPickerTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/gui",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
