java_test(
    name = "XMLBooleanTest",
    srcs = ["XMLBooleanTest.java"],
    deps = [
        "//java/believe/xml",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "XMLCompoundTest",
    srcs = ["XMLCompoundTest.java"],
    deps = [
        "//java/believe/xml",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "XMLIntegerTest",
    srcs = ["XMLIntegerTest.java"],
    deps = [
        "//java/believe/xml",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "XMLListTest",
    srcs = ["XMLListTest.java"],
    deps = [
        "//java/believe/xml",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "XMLNodeFactoryTest",
    srcs = ["XMLNodeFactoryTest.java"],
    deps = [
        "//java/believe/xml",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)

java_test(
    name = "XMLStringTest",
    srcs = ["XMLStringTest.java"],
    deps = [
        "//java/believe/xml",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
