java_test(
    name = "UtilTest",
    srcs = ["UtilTest.java"],
    test_class = "musicGame.util.UtilTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/geometry",
        "//src/musicGame/util",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
