filegroup(
    name = "res",
    srcs = [
        "//res/dialogue",
        "//res/graphics",
        "//res/maps",
        "//res/music",
        "//res/sfx",
    ],
    visibility = ["//:believe_all_pkgs"],
)
