load("//bazel/bzl:rules.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "LevelStateV2Test",
    srcs = ["LevelStateV2Test.kt"],
    deps = [
        "//java/believe/core/display:display_v2",
        "//java/believe/gamestate:gamestate_kt",
        "//java/believe/gamestate/levelstate:levelstate_v2",
        "//java/believe/gamestate/levelstate:levelstate_v2_impl",
        "//third_party/mockito:mockito_kotlin",
    ],
)
