java_test(
    name = "CharacterDialogueTest",
    srcs = ["CharacterDialogueTest.java"],
    deps = [
        "//java/believe/core/io/testing",
        "//java/believe/gui",
        "//java/believe/gui/testing",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "DirectionalPanelTest",
    srcs = ["DirectionalPanelTest.java"],
    deps = [
        "//java/believe/gui",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "MenuSelectionGroupTest",
    srcs = ["MenuSelectionGroupTest.java"],
    deps = [
        "//java/believe/gui",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
    ],
)

java_test(
    name = "NumberPickerTest",
    srcs = ["NumberPickerTest.java"],
    deps = [
        "//java/believe/audio",
        "//java/believe/gui",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
