java_test(
    name = "ComboSyncherTest",
    srcs = ["ComboSyncherTest.java"],
    test_class = "believe.levelFlow.component.ComboSyncherTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/believe/core",
        "//src/believe/levelFlow/component",
        "@junit//jar",
    ],
)

java_test(
    name = "BeatTest",
    srcs = ["BeatTest.java"],
    test_class = "believe.levelFlow.component.BeatTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/believe/levelFlow/component",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "FlowComponentIntegrationTest",
    srcs = ["FlowComponentIntegrationTest.java"],
    test_class = "believe.levelFlow.component.FlowComponentIntegrationTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/believe/levelFlow/component",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "FlowComponentTest",
    srcs = ["FlowComponentTest.java"],
    test_class = "believe.levelFlow.component.FlowComponentTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/believe/levelFlow/component",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "LaneTest",
    srcs = ["LaneTest.java"],
    test_class = "believe.levelFlow.component.LaneTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/believe/levelFlow/component",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
