java_test(
    name = "ComboSyncherTest",
    srcs = ["ComboSyncherTest.java"],
    test_class = "believe.levelFlow.component.ComboSyncherTest",
    deps = [
        "//src/believe/core",
        "//src/believe/levelFlow/component",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "BeatTest",
    srcs = ["BeatTest.java"],
    test_class = "believe.levelFlow.component.BeatTest",
    deps = [
        "//src/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "FlowComponentIntegrationTest",
    srcs = ["FlowComponentIntegrationTest.java"],
    test_class = "believe.levelFlow.component.FlowComponentIntegrationTest",
    deps = [
        "//src/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "FlowComponentTest",
    srcs = ["FlowComponentTest.java"],
    test_class = "believe.levelFlow.component.FlowComponentTest",
    deps = [
        "//src/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "LaneTest",
    srcs = ["LaneTest.java"],
    test_class = "believe.levelFlow.component.LaneTest",
    deps = [
        "//src/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
