java_library(
    name = "action",
    srcs = glob(["*.java"]),
    visibility = ["//src/musicGame/gamestate:__pkg__"],
    deps = [
        "//lib",
        "//src/musicGame/gamestate/base",
        "//src/musicGame/levelFlow/parsing/exceptions",
    ],
)
