package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "core",
    srcs = glob(["*.java"]),
    deps = [
        "//java/believe/xml",
        "//third_party/slick",
    ],
)
