java_library(
    name = "core",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/app:__pkg__",
        "//java/believe/character:character_pkg",
        "//java/believe/gamestate:__pkg__",
        "//java/believe/gui:__pkg__",
        "//java/believe/levelFlow/component:__pkg__",
        "//javatests/believe:believe_tests",
    ],
    deps = [
        "//java/believe/xml",
        "//third_party/slick",
    ],
)
