java_test(
    name = "PlatformingStateTest",
    srcs = ["PlatformingStateTest.java"],
    deps = [
        "//java/believe/core/io",
        "//java/believe/gamestate",
        "//java/believe/gamestate:package-info",
        "//java/believe/map/gui",
        "//java/believe/physics/manager",
        "//java/believe/testing",
        "//java/believe/util",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
