package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "command",
    srcs = [
        "Command.java",
        "CommandGenerator.java",
        "CommandSupplier.java",
    ],
    deps = [
        "//java/believe/core",
        "//third_party/dagger",
        "//third_party/javax:annotations",
        "//third_party/slick",
    ],
)
