java_test(
    name = "XMLBooleanTest",
    srcs = ["XMLBooleanTest.java"],
    test_class = "believe.xml.XMLBooleanTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//lib/mockito",
        "//lib/slick",
        "//src/believe/xml",
    ],
)

java_test(
    name = "XMLCompoundTest",
    srcs = ["XMLCompoundTest.java"],
    test_class = "believe.xml.XMLCompoundTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//lib/mockito",
        "//lib/slick",
        "//src/believe/xml",
    ],
)

java_test(
    name = "XMLIntegerTest",
    srcs = ["XMLIntegerTest.java"],
    test_class = "believe.xml.XMLIntegerTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//lib/mockito",
        "//lib/slick",
        "//src/believe/xml",
    ],
)

java_test(
    name = "XMLListTest",
    srcs = ["XMLListTest.java"],
    test_class = "believe.xml.XMLListTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//lib/mockito",
        "//lib/slick",
        "//src/believe/xml",
    ],
)

java_test(
    name = "XMLNodeFactoryTest",
    srcs = ["XMLNodeFactoryTest.java"],
    test_class = "believe.xml.XMLNodeFactoryTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//src/believe/xml",
    ],
)

java_test(
    name = "XMLStringTest",
    srcs = ["XMLStringTest.java"],
    test_class = "believe.xml.XMLStringTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//lib/mockito",
        "//lib/slick",
        "//src/believe/xml",
    ],
)
