java_library(
    name = "display",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/character:character_pkg",
        "//src/believe/gui:__pkg__",
        "//src/believe/levelFlow/component:__pkg__",
        "//src/believe/map/gui:__pkg__",
    ],
    deps = [
        "//lib/slick",
        "//src/believe/geometry",
        "//src/believe/xml",
    ],
)
