java_library(
    name = "statemachine",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/character:character_pkg",
        "//java/believe/map/collidable:__pkg__",
        "//java/believe/physics/collision:__pkg__",
        "//javatests/believe:believe_tests",
    ],
)
