package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "statemachine",
    srcs = [
        "ConcurrentStateMachine.java",
        "EntityStateMachine.java",
        "State.java",
        "Transition.java",
    ],
)
