java_library(
    name = "parsing",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/debug:__pkg__",
        "//src/musicGame/gamestate:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/levelFlow/component",
        "//src/musicGame/levelFlow/parsing/exceptions",
    ],
)
