package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "util",
    srcs = [
        "MapEntry.java",
        "Util.java",
    ],
    deps = [
        "//java/believe/geometry",
        "//third_party/slick",
    ],
)
