java_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/app:app_pkg",
        "//java/believe/character:character_pkg",
        "//java/believe/gamestate:__pkg__",
        "//java/believe/gui:__pkg__",
        "//java/believe/map/gui:__pkg__",
        "//javatests/believe:believe_tests",
    ],
    deps = [
        "//java/believe/geometry",
        "//third_party/slick",
    ],
)
