java_test(
    name = "TimerTest",
    srcs = ["TimerTest.java"],
    test_class = "musicGame.core.TimerTest",
    deps = [
        "//src/musicGame/core",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
