java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/gamestate:__pkg__",
        "//src/musicGame/gui:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/character",
        "//src/musicGame/character/playable",
        "//src/musicGame/core/display",
        "//src/musicGame/gui",
        "//src/musicGame/map/collidable",
        "//src/musicGame/map/io:properties",
        "//src/musicGame/util",
        "//src/musicGame/xml",
    ],
)
