java_test(
    name = "CrossFadeTransitionTest",
    srcs = ["CrossFadeTransitionTest.java"],
    test_class = "believe.graphics_transitions.CrossFadeTransitionTest",
    deps = [
        "//src/believe/graphics_transitions",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
