java_library(
    name = "exceptions",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/core/action:__pkg__",
        "//java/believe/debug:__pkg__",
        "//java/believe/gamestate:__pkg__",
        "//java/believe/levelFlow/parsing:__pkg__",
        "//javatests/believe:believe_tests",
    ],
)
