java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    visibility = [
        "//:believe_all_pkgs",
    ],
    deps = [
        "//lib/slick",
        "//src/believe/character",
        "//src/believe/character/playable",
        "//src/believe/core/display",
        "//src/believe/gui",
        "//src/believe/map/collidable",
        "//src/believe/map/io:properties",
        "//src/believe/util",
        "//src/believe/xml",
    ],
)
