java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/gamestate:__pkg__",
        "//src/believe/gui:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/believe/character",
        "//src/believe/character/playable",
        "//src/believe/core/display",
        "//src/believe/gui",
        "//src/believe/map/collidable",
        "//src/believe/map/io:properties",
        "//src/believe/util",
        "//src/believe/xml",
    ],
)
