java_test(
    name = "TileCollisionHandlerTest",
    srcs = ["TileCollisionHandlerTest.java"],
    deps = [
        "//java/believe/geometry",
        "//java/believe/map/collidable",
        "//java/believe/physics/collision",
        "//java/believe/physics/collision:handlers",
        "//third_party/junit",
        "//third_party/mockito",
    ],
)
