java_library(
    name = "manager",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/character:character_pkg",
        "//src/believe/gamestate:__pkg__",
        "//src/believe/physics/collision:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = [
        "//src/believe/physics/collision",
        "//src/believe/physics/gravity",
    ],
)
