java_library(
    name = "manager",
    srcs = glob(["*.java"]),
    visibility = ["//:believe_all_pkgs"],
    deps = [
        "//src/believe/physics/collision",
        "//src/believe/physics/gravity",
    ],
)
