package(
    default_visibility = [
        "//src/believe/app:app_pkg",
        "//test/believe:believe_tests",
    ],
)

java_library(
    name = "flags",
    srcs = glob(["*.java"]),
    deps = ["//src/believe/app/flag_parsers"],
)
