package(
    default_visibility = [
        "//java/believe/app:app_pkg",
        "//javatests/believe:believe_tests",
    ],
)

java_library(
    name = "flags",
    srcs = glob(["*.java"]),
    deps = ["//java/believe/app/flag_parsers"],
)
