java_library(
    name = "collidable",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/map/gui:__pkg__",
        "//src/musicGame/map/io:__pkg__",
        "//src/musicGame/physics/collision:__pkg__",
        "//test/musicGame/physics/collision:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/geometry",
        "//src/musicGame/map/io:map_entity_generator",
        "//src/musicGame/physics/collision",
        "//src/musicGame/statemachine",
    ],
)
