package(
    default_testonly = 1,
    default_visibility = ["//:believe_test_pkgs"],
)

java_library(
    name = "testing",
    srcs = [
        "FakeGuiContext.java",
        "FakeImage.java",
    ],
    deps = [
        "//third_party/lwjgl",
        "//third_party/slick",
    ],
)
