java_test(
    name = "MapPropertiesTest",
    srcs = ["MapPropertiesTest.java"],
    test_class = "musicGame.map.io.MapPropertiesTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/map/io:properties",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
