java_library(
    name = "debug",
    srcs = glob(["*.java"]),
    deps = [
        "//lib/slick",
        "//src/believe/levelFlow/parsing",
        "//src/believe/levelFlow/parsing/exceptions",
    ],
)
