java_library(
    name = "debug",
    srcs = glob(["*.java"]),
    deps = [
        "//src/believe/levelFlow/parsing",
        "//src/believe/levelFlow/parsing/exceptions",
        "//third_party/slick",
    ],
)
