java_library(
    name = "xml",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/core:__pkg__",
        "//src/believe/core/display:__pkg__",
        "//src/believe/map/gui:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = ["//lib/slick"],
)
