package(
    default_testonly = True,
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "testing",
    srcs = [
        "FakeCollidable.java",
        "package-info.java",
    ],
    deps = [
        "//java/believe/app/annotation",
        "//java/believe/geometry",
        "//java/believe/physics/collision",
        "//java/believe/util",
        "//third_party/javax:annotations",
    ],
)
