java_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/app:app_pkg",
        "//src/believe/character:character_pkg",
        "//src/believe/gamestate:__pkg__",
        "//src/believe/gui:__pkg__",
        "//src/believe/map/gui:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = [
        "//lib/slick",
        "//src/believe/geometry",
    ],
)
