java_library(
    name = "exceptions",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/core/action:__pkg__",
        "//src/musicGame/debug:__pkg__",
        "//src/musicGame/gamestate:__pkg__",
        "//src/musicGame/levelFlow/parsing:__pkg__",
        "//test/musicGame/levelFlow/parsing:__pkg__",
    ],
)
