java_test(
    name = "MapPropertiesTest",
    srcs = ["MapPropertiesTest.java"],
    test_class = "believe.map.io.MapPropertiesTest",
    deps = [
        "//lib",
        "//lib:hamcrest",
        "//lib:junit",
        "//lib:mockito",
        "//src/believe/map/io:properties",
    ],
)
