package(
    default_visibility = ["//:__pkg__"],
)

filegroup(
    name = "linux_x86",
    srcs = ["libjinput-linux.so"],
)

filegroup(
    name = "linux_x64",
    srcs = ["libjinput-linux64.so"],
)

filegroup(
    name = "mac",
    srcs = ["libjinput-osx.dylib"],
)
