java_test(
    name = "RectangleTest",
    srcs = ["RectangleTest.java"],
    test_class = "believe.geometry.RectangleTest",
    deps = [
        "//src/believe/geometry",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)
