java_test(
    name = "RectangleTest",
    srcs = ["RectangleTest.java"],
    test_class = "believe.geometry.RectangleTest",
    deps = [
        "//src/believe/geometry",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
