java_test(
    name = "RectangleTest",
    srcs = ["RectangleTest.java"],
    test_class = "believe.geometry.RectangleTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//src/believe/geometry",
    ],
)
