#!/bin/bash
# An exit status of 1 means that tests failed to run.

$(git rev-parse --show-toplevel)/dev/run_all_tests.sh || {
  echo "-------------------------------------------------------------------------------"
  echo "Push halted due to test failures."
  exit 1
}
