package(
    default_testonly = True,
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/lwjgl",
        "//third_party/slick",
    ],
)
