package(
    default_visibility = ["//javatests/believe:believe_tests"],
)

java_library(
    name = "testing",
    srcs = glob(["*.java"]),
    deps = [
        "//third_party/lwjgl",
        "//third_party/slick",
    ],
)
