load("//bazel/bzl:rules.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "CameraTest",
    srcs = ["CameraTest.kt"],
    deps = [
        "//java/believe/core/display",
        "//java/believe/geometry",
        "//java/believe/react:impl",
        "//java/believe/scene",
        "//third_party/mockito:mockito_kotlin",
    ],
)
