java_library(
    name = "debug",
    srcs = glob(["*.java"]),
    deps = [
        "//lib",
        "//src/musicGame/levelFlow/parsing",
        "//src/musicGame/levelFlow/parsing/exceptions",
    ],
)
