java_test(
    name = "PlatformingStateTest",
    srcs = ["PlatformingStateTest.java"],
    test_class = "believe.gamestate.PlatformingStateTest",
    deps = [
        "//src/believe/gamestate",
        "//src/believe/gamestate:package-info",
        "//src/believe/map/gui",
        "//src/believe/physics/manager",
        "//src/believe/testing",
        "//src/believe/util",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
