java_test(
    name = "PlatformingStateTest",
    srcs = ["PlatformingStateTest.java"],
    test_class = "believe.gamestate.PlatformingStateTest",
    deps = [
        "//lib",
        "//lib:junit",
        "//lib:mockito",
        "//src/believe/gamestate",
        "//src/believe/gamestate:package-info",
        "//src/believe/map/gui",
        "//src/believe/testing",
        "//src/believe/util",
    ],
)
