java_library(
    name = "xml",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/core:__pkg__",
        "//src/musicGame/core/display:__pkg__",
        "//src/musicGame/map/gui:__pkg__",
        "//test/musicGame/xml:__pkg__",
    ],
    deps = ["//lib"],
)
