java_test(
    name = "UtilTest",
    srcs = ["UtilTest.java"],
    test_class = "believe.util.UtilTest",
    deps = [
        "//lib/hamcrest",
        "//lib/junit",
        "//lib/mockito",
        "//lib/slick",
        "//src/believe/geometry",
        "//src/believe/util",
    ],
)
