java_test(
    name = "UtilTest",
    srcs = ["UtilTest.java"],
    test_class = "believe.util.UtilTest",
    deps = [
        "//src/believe/geometry",
        "//src/believe/util",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
