java_test(
    name = "UtilTest",
    srcs = ["UtilTest.java"],
    test_class = "believe.util.UtilTest",
    deps = [
        "//lib",
        "//lib:hamcrest",
        "//lib:junit",
        "//lib:mockito",
        "//src/believe/geometry",
        "//src/believe/util",
    ],
)
