java_library(
    name = "parsing",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/debug:__pkg__",
        "//java/believe/gamestate:__pkg__",
        "//javatests/believe:believe_tests",
    ],
    deps = [
        "//java/believe/levelFlow/component",
        "//java/believe/levelFlow/parsing/exceptions",
        "//third_party/slick",
    ],
)
