package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "parsing",
    srcs = glob(["*.java"]),
    deps = [
        "//java/believe/levelFlow/component",
        "//java/believe/levelFlow/parsing/exceptions",
        "//third_party/slick",
    ],
)
