java_library(
    name = "core",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/app:__pkg__",
        "//src/believe/character:character_pkg",
        "//src/believe/gamestate:__pkg__",
        "//src/believe/gui:__pkg__",
        "//src/believe/levelFlow/component:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = [
        "//lib",
        "//src/believe/xml",
    ],
)
