package(
    default_visibility = [
        "//java/believe/app:app_pkg",
        "//javatests/believe:believe_tests",
    ],
)

java_library(
    name = "flag_parsers",
    srcs = glob(["*.java"]),
    deps = [],
)
