java_library(
    name = "xml",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/core:__pkg__",
        "//java/believe/core/display:__pkg__",
        "//java/believe/map/gui:__pkg__",
        "//javatests/believe:believe_tests",
    ],
    deps = ["//third_party/slick"],
)
