load("//bazel/bzl:rules.bzl", "java_junit5_test")

java_junit5_test(
    name = "FakeCollidableTest",
    srcs = ["FakeCollidableTest.java"],
    deps = [
        "//java/believe/geometry",
        "//java/believe/physics/collision",
        "//java/believe/physics/collision/testing",
        "//java/believe/testing/mockito",
        "//java/believe/util",
        "//third_party/mockito",
        "//third_party/truth",
    ],
)
