java_library(
    name = "statemachine",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/character:character_pkg",
        "//src/believe/map/collidable:__pkg__",
        "//src/believe/physics/collision:__pkg__",
        "//test/believe:believe_tests",
    ],
)
