java_test(
    name = "IntegerFlagParserTest",
    srcs = ["IntegerFlagParserTest.java"],
    deps = [
        "//java/believe/app/flag_parsers",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)

java_test(
    name = "BooleanFlagParserTest",
    srcs = ["BooleanFlagParserTest.java"],
    deps = [
        "//java/believe/app/flag_parsers",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)

java_test(
    name = "CommandLineParserTest",
    srcs = ["CommandLineParserTest.java"],
    deps = [
        "//java/believe/app/flag_parsers",
        "//third_party/hamcrest",
        "//third_party/junit",
    ],
)
