package(
    default_visibility = ["//:__pkg__"],
)

java_library(
    name = "editor",
    srcs = glob(["*.java"]),
    deps = [
        "//java/believe/app",
        "//java/believe/app/flag_parsers",
        "//java/believe/app/flags",
        "//java/believe/core/io",
        "//java/believe/gamestate",
        "//java/believe/map/gui",
        "//java/believe/physics/manager",
        "//java/believe/util",
        "//third_party/slick",
    ],
)
