package(
    default_visibility = [
        "//src/believe/app:app_pkg",
        "//test/believe:believe_tests",
    ],
)

java_library(
    name = "flag_parsers",
    srcs = glob(["*.java"]),
    deps = [],
)
