java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/character:character_pkg",
        "//src/believe/gamestate:__pkg__",
        "//src/believe/levelFlow/component:__pkg__",
        "//src/believe/map/gui:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = [
        "//lib/slick",
        "//src/believe/core",
        "//src/believe/core/display",
        "//src/believe/geometry",
        "//src/believe/util",
    ],
)
