java_library(
    name = "graphics_transitions",
    srcs = [
        "CrossFadeTransition.java",
        "GraphicsTransitionPairFactory.java",
    ],
    visibility = ["//:believe_all_pkgs"],
    deps = ["//lib/slick"],
)
