java_library(
    name = "gravity",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/physics/collision:__pkg__",
        "//src/musicGame/physics/manager:__pkg__",
        "//test/musicGame:believe_tests",
    ],
)
