java_library(
    name = "core",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame:__pkg__",
        "//src/musicGame/character:character_pkg",
        "//src/musicGame/gamestate:__pkg__",
        "//src/musicGame/gui:__pkg__",
        "//src/musicGame/levelFlow/component:__pkg__",
        "//test/musicGame/core:__pkg__",
        "//test/musicGame/gui:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/xml",
    ],
)
