java_library(
    name = "geometry",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/character:character_pkg",
        "//src/believe/core/display:__pkg__",
        "//src/believe/gui:__pkg__",
        "//src/believe/levelFlow/component:__pkg__",
        "//src/believe/map/collidable:__pkg__",
        "//src/believe/physics/collision:__pkg__",
        "//src/believe/util:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = ["//lib"],
)
