java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    visibility = ["//src/musicGame/gamestate:__pkg__"],
    deps = [
        "//lib",
        "//src/musicGame/core",
        "//src/musicGame/core/display",
        "//src/musicGame/gui/base",
        "//src/musicGame/levelFlow/component",
        "//src/musicGame/map/gui",
        "//src/musicGame/util",
    ],
)
