java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character:character_pkg",
        "//src/musicGame/gamestate:__pkg__",
        "//src/musicGame/levelFlow/component:__pkg__",
        "//src/musicGame/map/gui:__pkg__",
        "//test/musicGame:believe_tests",
    ],
    deps = [
        "//lib",
        "//src/musicGame/core",
        "//src/musicGame/core/display",
        "//src/musicGame/geometry",
        "//src/musicGame/util",
    ],
)
