java_test(
    name = "ComboSyncherTest",
    srcs = ["ComboSyncherTest.java"],
    deps = [
        "//java/believe/core",
        "//java/believe/levelFlow/component",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "BeatTest",
    srcs = ["BeatTest.java"],
    deps = [
        "//java/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "FlowComponentIntegrationTest",
    srcs = ["FlowComponentIntegrationTest.java"],
    deps = [
        "//java/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "FlowComponentTest",
    srcs = ["FlowComponentTest.java"],
    deps = [
        "//java/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "LaneTest",
    srcs = ["LaneTest.java"],
    deps = [
        "//java/believe/levelFlow/component",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
