java_library(
    name = "statemachine",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character:__pkg__",
        "//src/musicGame/character/base:__pkg__",
        "//src/musicGame/map/collidable:__pkg__",
        "//src/musicGame/physics/collision:__pkg__",
        "//test/musicGame/statemachine:__pkg__",
    ],
)
