java_library(
    name = "base",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame:__pkg__",
        "//src/musicGame/core/action:__pkg__",
        "//src/musicGame/gamestate:__pkg__",
    ],
    deps = ["//lib"],
)
