package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "dialogue",
    srcs = [
        "DialogueManager.java",
        "package-info.java",
    ],
    deps = [
        "//java/believe/app/annotation",
        "//java/believe/dialogue/proto:dialogue_java_proto",
        "//third_party/javax:annotations",
        "//third_party/slick",
    ],
)
