package(default_visibility = ["//:believe_all_pkgs"])

proto_library(
    name = "mob_animation_data_proto",
    srcs = ["mob_animation_data.proto"],
)

java_proto_library(
    name = "mob_animation_data_java_proto",
    deps = [":mob_animation_data_proto"],
)
