java_library(
    name = "manager",
    srcs = [
        "PhysicsManageable.java",
        "PhysicsManager.java",
    ],
    visibility = ["//:believe_all_pkgs"],
    deps = [
        "//java/believe/physics/collision",
        "//java/believe/physics/gravity",
        "//third_party/javax:annotations",
    ],
)
