package(default_visibility = ["//:__pkg__"])

filegroup(
    name = "windows_x86",
    srcs = [
        "OpenAL32.dll",
        "lwjgl.dll",
    ],
)

filegroup(
    name = "windows_x64",
    srcs = [
        "OpenAL64.dll",
        "lwjgl64.dll",
    ],
)

filegroup(
    name = "linux_x86",
    srcs = [
        "libjinput-linux.so",
        "liblwjgl.so",
        "libopenal.so",
    ],
)

filegroup(
    name = "linux_x64",
    srcs = [
        "libjinput-linux64.so",
        "liblwjgl64.so",
        "libopenal64.so",
    ],
)

filegroup(
    name = "mac",
    srcs = [
        "libjinput-osx.dylib",
        "liblwjgl.dylib",
        "openal.dylib",
    ],
)
