java_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character:character_pkg",
        "//src/musicGame/gamestate:__pkg__",
        "//src/musicGame/gui:__pkg__",
        "//test/musicGame:believe_tests",
    ],
    deps = [
        "//lib",
        "//src/musicGame/geometry",
    ],
)
