java_library(
    name = "util",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character:__pkg__",
        "//src/musicGame/character/base:__pkg__",
        "//src/musicGame/gamestate:__pkg__",
        "//src/musicGame/gui:__pkg__",
        "//test/musicGame/statemachine:__pkg__",
        "//test/musicGame/util:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/geometry",
    ],
)
