package(
    default_testonly = 1,
    default_visibility = ["//visibility:private"],
)

java_test(
    name = "VerifiableLogSystemExtensionTest",
    srcs = ["VerifiableLogSystemExtensionTest.java"],
    deps = [
        "//java/believe/logging/testing",
        "//java/believe/logging/testing:package_info",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
        "//third_party/truth",
    ],
)

java_test(
    name = "VerifiableLogSystemTest",
    srcs = ["VerifiableLogSystemTest.java"],
    deps = [
        "//java/believe/logging/testing",
        "//java/believe/logging/testing:package_info",
        "//third_party/truth",
    ],
)
