java_library(
    name = "display",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/musicGame/character/base:__pkg__",
        "//src/musicGame/gui:__pkg__",
        "//src/musicGame/map/gui:__pkg__",
    ],
    deps = [
        "//lib",
        "//src/musicGame/geometry",
        "//src/musicGame/xml",
    ],
)
