java_test(
    name = "FlowComponentBuilderTest",
    srcs = ["FlowComponentBuilderTest.java"],
    test_class = "musicGame.levelFlow.parsing.FlowComponentBuilderTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/levelFlow/parsing",
        "//src/musicGame/levelFlow/parsing/exceptions",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "FlowFileParserIntegrationTest",
    srcs = ["FlowFileParserIntegrationTest.java"],
    test_class = "musicGame.levelFlow.parsing.FlowFileParserIntegrationTest",
    deps = [
        "//lib",
        "//src/musicGame/levelFlow/parsing",
        "//src/musicGame/levelFlow/parsing/exceptions",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "FlowFileParserTest",
    srcs = ["FlowFileParserTest.java"],
    test_class = "musicGame.levelFlow.parsing.FlowFileParserTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/levelFlow/parsing",
        "//src/musicGame/levelFlow/parsing/exceptions",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "FlowFileTokenizerTest",
    srcs = ["FlowFileTokenizerTest.java"],
    test_class = "musicGame.levelFlow.parsing.FlowFileTokenizerTest",
    deps = [
        "//src/musicGame/levelFlow/parsing",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "LineParserTest",
    srcs = ["LineParserTest.java"],
    test_class = "musicGame.levelFlow.parsing.LineParserTest",
    deps = [
        "//src/musicGame/levelFlow/parsing",
        "//src/musicGame/levelFlow/parsing/exceptions",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
