java_library(
    name = "display",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/character:character_pkg",
        "//java/believe/gui:__pkg__",
        "//java/believe/levelFlow/component:__pkg__",
        "//java/believe/map/gui:__pkg__",
    ],
    deps = [
        "//java/believe/geometry",
        "//java/believe/xml",
        "//third_party/slick",
    ],
)
