package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "display",
    srcs = [
        "AnimationSet.java",
        "Renderable.java",
        "SpriteSheetManager.java",
    ],
    deps = [
        "//java/believe/geometry",
        "//java/believe/xml",
        "//third_party/slick",
    ],
)
