package(
    default_visibility = ["//:believe_all_pkgs"],
)

proto_library(
    name = "animation_proto",
    srcs = ["animation.proto"],
)

java_proto_library(
    name = "animation_java_proto",
    deps = [":animation_proto"],
)
