package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "gui",
    srcs = [
        "LevelMap.java",
        "MapBackground.java",
        "MapLayerComponent.java",
        "PlayArea.java",
        "package-info.java",
    ],
    deps = [
        "//java/believe/app/annotation",
        "//java/believe/character",
        "//java/believe/character/playable",
        "//java/believe/core",
        "//java/believe/core/display",
        "//java/believe/gui",
        "//java/believe/map/collidable/command",
        "//java/believe/map/data",
        "//java/believe/map/io",
        "//java/believe/util",
        "//third_party/auto_factory",
        "//third_party/javax:annotations",
        "//third_party/slick",
    ],
)
