java_library(
    name = "gui",
    srcs = glob(["*.java"]),
    visibility = [
        "//:believe_all_pkgs",
    ],
    deps = [
        "//java/believe/character",
        "//java/believe/character/playable",
        "//java/believe/core/display",
        "//java/believe/gui",
        "//java/believe/map/collidable",
        "//java/believe/map/io:properties",
        "//java/believe/util",
        "//java/believe/xml",
        "//third_party/slick",
    ],
)
