java_test(
    name = "RectangleTest",
    srcs = ["RectangleTest.java"],
    test_class = "musicGame.geometry.RectangleTest",
    deps = [
        "//src/musicGame/geometry",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
