java_library(
    name = "parsing",
    srcs = glob(["*.java"]),
    visibility = [
        "//src/believe/debug:__pkg__",
        "//src/believe/gamestate:__pkg__",
        "//test/believe:believe_tests",
    ],
    deps = [
        "//lib/slick",
        "//src/believe/levelFlow/component",
        "//src/believe/levelFlow/parsing/exceptions",
    ],
)
