package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "tiled",
    srcs = [
        "EntityType.java",
        "Layer.java",
        "Tile.java",
        "TileSet.java",
        "TiledMap.java",
        "TiledMapObjectPropertyProvider.java",
        "TiledObject.java",
        "TiledUtil.java",
        "package-info.java",
    ],
    deps = [
        "//java/believe/app/annotation",
        "//java/believe/core",
        "//third_party/auto_value",
        "//third_party/javax:annotations",
        "//third_party/slick",
    ],
)
