package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "tiled",
    srcs = [
        "EntityType.java",
        "Layer.java",
        "Tile.java",
        "TileSet.java",
        "TiledMap.java",
        "TiledUtil.java",
    ],
    deps = [
        "//third_party/auto_value",
        "//third_party/slick",
    ],
)
