java_library(
    name = "component",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/gamestate:__pkg__",
        "//java/believe/gui:__pkg__",
        "//java/believe/levelFlow/parsing:__pkg__",
        "//javatests/believe:believe_tests",
    ],
    deps = [
        "//java/believe/core",
        "//java/believe/core/display",
        "//java/believe/core/io",
        "//java/believe/geometry",
        "//java/believe/gui",
        "//third_party/slick",
    ],
)
