package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "component",
    srcs = glob(["*.java"]),
    deps = [
        "//java/believe/audio",
        "//java/believe/core",
        "//java/believe/core/display",
        "//java/believe/core/io",
        "//java/believe/geometry",
        "//java/believe/gui",
        "//third_party/slick",
    ],
)
