package(
    default_testonly = True,
    default_visibility = ["//:believe_test_pkgs"],
)

java_library(
    name = "testing",
    srcs = ["FakeTiledMap.java"],
    deps = ["//java/believe/map/tiled"],
)
