package(
    default_testonly = True,
    default_visibility = ["//:believe_test_pkgs"],
)

java_library(
    name = "testing",
    srcs = [
        "FakeTiledMap.java",
        "FakeTiledObjectFactory.java",
        "package-info.java",
    ],
    deps = [
        "//java/believe/app/annotation",
        "//java/believe/map/tiled",
        "//third_party/javax:annotations",
    ],
)
