java_library(
    name = "gamestate",
    srcs = glob(["*.java"]),
    visibility = ["//src/musicGame:__pkg__"],
    deps = [
        "//lib",
        "//src/musicGame/character/playable",
        "//src/musicGame/core",
        "//src/musicGame/core/action",
        "//src/musicGame/gamestate/base",
        "//src/musicGame/gui",
        "//src/musicGame/levelFlow/component",
        "//src/musicGame/levelFlow/parsing",
        "//src/musicGame/levelFlow/parsing/exceptions",
        "//src/musicGame/map/gui",
        "//src/musicGame/physics/manager",
        "//src/musicGame/util",
    ],
)
