load("//bazel/bzl:rules.bzl", "kt_junit5_test")

kt_junit5_test(
    name = "StationaryEnemyParserTest",
    srcs = ["StationaryEnemyParserTest.kt"],
    deps = [
        "//java/believe/map/data",
        "//java/believe/map/tiled/testing",
        "//java/believe/mob",
        "//third_party/truth",
    ],
)
