java_library(
    name = "geometry",
    srcs = glob(["*.java"]),
    visibility = [
        "//java/believe/character:character_pkg",
        "//java/believe/core/display:__pkg__",
        "//java/believe/gui:__pkg__",
        "//java/believe/levelFlow/component:__pkg__",
        "//java/believe/map/collidable:__pkg__",
        "//java/believe/physics/collision:__pkg__",
        "//java/believe/util:__pkg__",
        "//javatests/believe:believe_tests",
    ],
    deps = ["//third_party/slick"],
)
