java_test(
    name = "DamageProjectionTest",
    srcs = ["DamageProjectionTest.java"],
    test_class = "believe.character.playable.DamageProjectionTest",
    deps = [
        "//src/believe/character",
        "//src/believe/character/playable",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
