java_test(
    name = "XMLBooleanTest",
    srcs = ["XMLBooleanTest.java"],
    test_class = "musicGame.xml.XMLBooleanTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/xml",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "XMLCompoundTest",
    srcs = ["XMLCompoundTest.java"],
    test_class = "musicGame.xml.XMLCompoundTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/xml",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "XMLIntegerTest",
    srcs = ["XMLIntegerTest.java"],
    test_class = "musicGame.xml.XMLIntegerTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/xml",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "XMLListTest",
    srcs = ["XMLListTest.java"],
    test_class = "musicGame.xml.XMLListTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/xml",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "XMLNodeFactoryTest",
    srcs = ["XMLNodeFactoryTest.java"],
    test_class = "musicGame.xml.XMLNodeFactoryTest",
    deps = [
        "//src/musicGame/xml",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "XMLStringTest",
    srcs = ["XMLStringTest.java"],
    test_class = "musicGame.xml.XMLStringTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/musicGame/xml",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
