java_test(
    name = "FlowComponentBuilderTest",
    srcs = ["FlowComponentBuilderTest.java"],
    test_class = "believe.levelFlow.parsing.FlowComponentBuilderTest",
    deps = [
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
        "//src/believe/levelFlow/parsing",
        "//src/believe/levelFlow/parsing/exceptions",
    ],
)

java_test(
    name = "FlowFileParserIntegrationTest",
    srcs = ["FlowFileParserIntegrationTest.java"],
    test_class = "believe.levelFlow.parsing.FlowFileParserIntegrationTest",
    deps = [
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/slick",
        "//src/believe/levelFlow/parsing",
        "//src/believe/levelFlow/parsing/exceptions",
    ],
)

java_test(
    name = "FlowFileParserTest",
    srcs = ["FlowFileParserTest.java"],
    test_class = "believe.levelFlow.parsing.FlowFileParserTest",
    deps = [
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
        "//src/believe/levelFlow/parsing",
        "//src/believe/levelFlow/parsing/exceptions",
    ],
)

java_test(
    name = "FlowFileTokenizerTest",
    srcs = ["FlowFileTokenizerTest.java"],
    test_class = "believe.levelFlow.parsing.FlowFileTokenizerTest",
    deps = [
        "//third_party/hamcrest",
        "//third_party/junit",
        "//src/believe/levelFlow/parsing",
    ],
)

java_test(
    name = "LineParserTest",
    srcs = ["LineParserTest.java"],
    test_class = "believe.levelFlow.parsing.LineParserTest",
    deps = [
        "//third_party/hamcrest",
        "//third_party/junit",
        "//src/believe/levelFlow/parsing",
        "//src/believe/levelFlow/parsing/exceptions",
    ],
)
