java_library(
    name = "io",
    srcs = [
        "FontLoader.java",
        "JarClasspathLocation.java",
        "ReloadableFileSystemLocation.java",
    ],
    visibility = ["//:believe_all_pkgs"],
    deps = [
        "//third_party/dagger",
        "//third_party/javax:annotations",
        "//third_party/slick",
    ],
)
