java_test(
    name = "TileCollisionHandlerTest",
    srcs = ["TileCollisionHandlerTest.java"],
    test_class = "believe.physics.collision.TileCollisionHandlerTest",
    deps = [
        "//lib:mockito",
        "//src/believe/geometry",
        "//src/believe/map/collidable",
        "//src/believe/physics/collision",
        "//src/believe/physics/collision:handlers",
        "@junit//jar",
    ],
)
