java_test(
    name = "TileCollisionHandlerTest",
    srcs = ["TileCollisionHandlerTest.java"],
    test_class = "believe.physics.collision.TileCollisionHandlerTest",
    deps = [
        "//src/believe/geometry",
        "//src/believe/map/collidable",
        "//src/believe/physics/collision",
        "//src/believe/physics/collision:handlers",
        "//third_party/junit",
        "//third_party/mockito",
    ],
)
