package(
    default_visibility = ["//:believe_all_pkgs"],
)

java_library(
    name = "data",
    srcs = [
        "BackgroundSceneData.java",
        "GeneratedMapEntityData.java",
        "LayerData.java",
        "MapData.java",
        "package-info.java",
    ],
    deps = [
        "//java/believe/app/annotation",
        "//java/believe/core",
        "//java/believe/core/display",
        "//java/believe/map/tiled",
        "//java/believe/physics/manager",
        "//third_party/auto_value",
        "//third_party/javax:annotations",
        "//third_party/slick",
    ],
)
