java_library(
    name = "playable",
    srcs = glob(["*.java"]),
    visibility = [
        "//:believe_all_pkgs",
    ],
    deps = [
        "//java/believe/character",
        "//java/believe/character:faction",
        "//java/believe/core",
        "//java/believe/core/display",
        "//java/believe/map/io:map_entity_generator",
        "//java/believe/physics/collision",
        "//java/believe/physics/collision:handlers",
        "//java/believe/physics/gravity",
        "//java/believe/physics/manager",
        "//java/believe/statemachine",
        "//java/believe/util",
        "//third_party/javax:annotations",
        "//third_party/slick",
    ],
)
