@ParametersAreNonnullByDefault @ReturnTypesAreNonnulByDefault @FieldsAreNonnulByDefault
package believe.character.playable;

import believe.app.annotation.Nullability.FieldsAreNonnulByDefault;
import believe.app.annotation.Nullability.ReturnTypesAreNonnulByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
