java_test(
    name = "DirectionalPanelTest",
    srcs = ["DirectionalPanelTest.java"],
    test_class = "believe.gui.DirectionalPanelTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/believe/gui",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "MenuSelectionGroupTest",
    srcs = ["MenuSelectionGroupTest.java"],
    test_class = "believe.gui.MenuSelectionGroupTest",
    deps = [
        "//lib:mockito",
        "//src/believe/gui",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)

java_test(
    name = "NumberPickerTest",
    srcs = ["NumberPickerTest.java"],
    test_class = "believe.gui.NumberPickerTest",
    deps = [
        "//lib",
        "//lib:mockito",
        "//src/believe/gui",
        "@hamcrest//jar",
        "@junit//jar",
    ],
)
