java_test(
    name = "CharacterDialogueTest",
    srcs = ["CharacterDialogueTest.java"],
    test_class = "believe.gui.CharacterDialogueTest",
    deps = [
        "//src/believe/gui",
        "//third_party/junit",
        "//third_party/slick",
    ],
)

java_test(
    name = "DirectionalPanelTest",
    srcs = ["DirectionalPanelTest.java"],
    test_class = "believe.gui.DirectionalPanelTest",
    deps = [
        "//src/believe/gui",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)

java_test(
    name = "MenuSelectionGroupTest",
    srcs = ["MenuSelectionGroupTest.java"],
    test_class = "believe.gui.MenuSelectionGroupTest",
    deps = [
        "//src/believe/gui",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
    ],
)

java_test(
    name = "NumberPickerTest",
    srcs = ["NumberPickerTest.java"],
    test_class = "believe.gui.NumberPickerTest",
    deps = [
        "//src/believe/gui",
        "//third_party/hamcrest",
        "//third_party/junit",
        "//third_party/mockito",
        "//third_party/slick",
    ],
)
